contact_links:
  - name: Discord server ↪
    url: https://discord.gg/pJkm23b2nA
    about: Discuss or get help on the Discord server
  - name: Subreddit ↪
    url: https://reddit.com/r/placeAtlas2
    about: Discuss or get help on the subreddit