name: Validate JSON
on:
  push:
    paths:
      - web/atlas.json
  pull_request:
    paths:
      - web/atlas.json
jobs:
  Validate-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Validate JSON
        run: |
          chmod +x ${{ github.workspace }}/tools/validate_json.py
          python3 ${{ github.workspace }}/tools/validate_json.py ${{ github.workspace }}/docs/atlas.json